image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - eamodio.gitlens
    - davidanson.vscode-markdownlint
    - amazonwebservices.aws-toolkit-vscode
    - ms-python.python

tasks:
- command: sudo rm /var/run/docker.sock && sudo docker-up
